#!/bin/bash
# Manual deployment guide for deepfake detection system

echo "🌐 Deepfake Detection System - Manual Deployment Guide"
echo "====================================================="
echo ""

echo "Since Heroku CLI requires sudo access, let's use alternative methods:"
echo ""

echo "🚀 OPTION 1: Railway (Easiest - No sudo required)"
echo "================================================"
echo "1. Install Railway CLI:"
echo "   npm install -g @railway/cli"
echo ""
echo "2. Login and deploy:"
echo "   railway login"
echo "   railway init"
echo "   railway up"
echo ""

echo "🚀 OPTION 2: Render (Web-based - No CLI needed)"
echo "=============================================="
echo "1. Go to https://render.com"
echo "2. Sign up with GitHub"
echo "3. Create new Web Service"
echo "4. Connect your repository"
echo "5. Use these settings:"
echo "   - Build Command: pip install -r requirements_production.txt"
echo "   - Start Command: gunicorn app_production:app --bind 0.0.0.0:\$PORT"
echo "   - Python Version: 3.12"
echo ""

echo "🚀 OPTION 3: Vercel (Serverless - No sudo required)"
echo "=================================================="
echo "1. Install Vercel CLI:"
echo "   npm install -g vercel"
echo ""
echo "2. Deploy:"
echo "   vercel login"
echo "   vercel --prod"
echo ""

echo "🚀 OPTION 4: Fly.io (Global Edge - No sudo required)"
echo "==================================================="
echo "1. Install Fly CLI:"
echo "   curl -L https://fly.io/install.sh | sh"
echo ""
echo "2. Deploy:"
echo "   flyctl auth login"
echo "   flyctl launch"
echo "   flyctl deploy"
echo ""

echo "🚀 OPTION 5: Google Cloud Run (Free tier)"
echo "========================================="
echo "1. Go to https://console.cloud.google.com"
echo "2. Create new project"
echo "3. Enable Cloud Run API"
echo "4. Use Cloud Shell to deploy"
echo ""

echo "📋 Quick Start - Choose One:"
echo "============================"
echo ""
echo "For Railway (Recommended):"
echo "  npm install -g @railway/cli"
echo "  railway login"
echo "  railway init"
echo "  railway up"
echo ""
echo "For Render (Web-based):"
echo "  1. Push to GitHub first:"
echo "     git remote add origin https://github.com/yourusername/deepfake-detector.git"
echo "     git push -u origin main"
echo "  2. Go to render.com and connect GitHub"
echo ""
echo "For Vercel:"
echo "  npm install -g vercel"
echo "  vercel login"
echo "  vercel --prod"
echo ""

echo "🎯 After deployment, your app will be live at:"
echo "   Railway: https://your-app.railway.app"
echo "   Render: https://your-app.onrender.com"
echo "   Vercel: https://your-app.vercel.app"
echo "   Fly.io: https://your-app.fly.dev"
echo ""

echo "🌍 Your deepfake detection system will be permanently accessible worldwide!"
