version: '3.8'

services:
  deepfake-detector:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    volumes:
      - ./models:/app/models
      - ./uploads:/app/uploads
      - ./static/results:/app/static/results
    restart: unless-stopped
